"""Tests for autofix_configworkflow_docs.py."""

import os
import sys
import unittest


TEST_DIR = os.path.dirname(os.path.abspath(__file__))
REPO_ROOT = os.path.join(TEST_DIR, "..", "..")
sys.path.insert(0, os.path.join(REPO_ROOT, "scripts"))

from autofix_configworkflow_docs import (  # pylint: disable=wrong-import-position
    replace_inline_default,
    upsert_auto_section,
)
from check_configworkflow_docs import VariableChange  # pylint: disable=wrong-import-position


class TestAutofixConfigWorkflowDocs(unittest.TestCase):
    """Unit tests for config doc autofix behavior."""

    def test_replace_inline_default(self):
        """Update an existing inline default."""

        text = '``PT_SRC_SUBDIR``: (Default: ``"old"``)\n'
        updated = replace_inline_default(text, "PT_SRC_SUBDIR", '"new"')
        self.assertEqual(updated, '``PT_SRC_SUBDIR``: (Default: ``"new"``)\n')

    def test_upsert_auto_section(self):
        """Insert an autogenerated section before the Rocoto heading."""

        text = "Header\n\nRocoto Parameters\n===================\n"
        updated = upsert_auto_section(
            text,
            [VariableChange(name="NEW_VAR", new="false")],
        )
        self.assertIn("Auto-Generated Pending Documentation", updated)
        self.assertIn("``NEW_VAR``", updated)
        self.assertIn("Rocoto Parameters", updated)


if __name__ == "__main__":
    unittest.main()
