"""Autofix ConfigWorkflow.rst drift for config_defaults.yaml changes."""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

from check_configworkflow_docs import (  # pylint: disable=import-error
    CONFIG_PATH,
    DOC_PATH,
    REPO_ROOT,
    VariableChange,
    build_snippet,
    extract_doc_default,
    get_diff_text,
    has_variable_doc,
    normalize_default,
    parse_changed_variables,
)


AUTO_START = ".. BEGIN AUTO-GENERATED CONFIG DOCS"
AUTO_END = ".. END AUTO-GENERATED CONFIG DOCS"
AUTO_SECTION = """Auto-Generated Pending Documentation
----------------------------------

The entries below were auto-generated from ``config_defaults.yaml`` because this PR
changed config variables without fully documenting them in this chapter. Review and
move them to the appropriate section before merge.
"""


def parse_args() -> argparse.Namespace:
    """Parse CLI args."""

    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--base-ref",
        required=True,
        help="Git ref to compare against, e.g. origin/develop",
    )
    return parser.parse_args()


def format_doc_default(value: str | None) -> str:
    """Format a config default for inline RST use."""

    if value is None:
        return "unknown"
    stripped = value.strip()
    if re.fullmatch(r"-?\d+(\.\d+)?", stripped):
        return stripped
    if stripped in {"true", "false", "null", "[]", "{}"}:
        return stripped
    return f"``{stripped}``"


def replace_inline_default(doc_text: str, name: str, new_value: str) -> str:
    """Replace an inline documented default for one variable."""

    pattern = re.compile(
        rf"(^``{re.escape(name)}``:\s+\(Default:\s*)(.*?)(\)\s*$)",
        re.MULTILINE,
    )
    replacement = rf"\1{format_doc_default(new_value)}\3"
    return pattern.sub(replacement, doc_text, count=1)


def render_auto_section(missing_changes: list[VariableChange]) -> str:
    """Render the auto-generated section."""

    parts = [
        AUTO_START,
        "",
        AUTO_SECTION.rstrip(),
        "",
    ]
    for change in missing_changes:
        parts.append(build_snippet(change.name, change.new).rstrip())
        parts.append("")
    parts.append(AUTO_END)
    parts.append("")
    return "\n".join(parts)


def upsert_auto_section(doc_text: str, missing_changes: list[VariableChange]) -> str:
    """Insert, replace, or remove the auto-generated section."""

    pattern = re.compile(
        rf"\n?{re.escape(AUTO_START)}.*?{re.escape(AUTO_END)}\n?",
        re.DOTALL,
    )
    has_section = pattern.search(doc_text) is not None

    if not missing_changes:
        return pattern.sub("\n", doc_text) if has_section else doc_text

    block = render_auto_section(missing_changes)
    if has_section:
        return pattern.sub(f"\n{block}\n", doc_text)

    anchor = "\nRocoto Parameters\n===================\n"
    if anchor in doc_text:
        return doc_text.replace(anchor, f"\n{block}{anchor}", 1)
    return f"{doc_text.rstrip()}\n\n{block}"


def apply_autofix(base_ref: str) -> tuple[bool, list[str]]:
    """Apply doc autofixes and return whether the file changed plus a summary."""

    diff_text = get_diff_text(base_ref)
    added_changes, removed_changes, modified_changes = parse_changed_variables(diff_text)
    doc_path = REPO_ROOT / DOC_PATH
    doc_text = doc_path.read_text(encoding="utf-8")
    original = doc_text
    summary: list[str] = []

    for change in modified_changes:
        if not has_variable_doc(doc_text, change.name):
            continue
        doc_default = extract_doc_default(doc_text, change.name)
        if doc_default is None:
            continue
        if normalize_default(doc_default) == normalize_default(change.new):
            continue
        doc_text = replace_inline_default(doc_text, change.name, change.new or "")
        summary.append(f"Updated default for {change.name}")

    missing_changes: list[VariableChange] = []
    for change in [*added_changes, *modified_changes]:
        if not has_variable_doc(doc_text, change.name):
            missing_changes.append(change)

    doc_text = upsert_auto_section(doc_text, missing_changes)
    if missing_changes:
        summary.append(f"Added/updated autogenerated stub section for {len(missing_changes)} variable(s)")

    if doc_text != original:
        doc_path.write_text(doc_text, encoding="utf-8")
        return True, summary
    return False, summary


def main() -> int:
    """CLI entry point."""

    args = parse_args()
    changed, summary = apply_autofix(args.base_ref)
    if changed:
        print(f"Updated {DOC_PATH}")
        for line in summary:
            print(f"- {line}")
    else:
        print(f"No autofix changes were needed for {DOC_PATH}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
